mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #核心配置文件路径
  config-location: classpath:mybatis/config.xml
spring:
    datasource:
        primary:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8
            password: admin
            username: root
        secondary:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
            password: admin
            username: root
        secondary3:
            driverClassName: oracle.jdbc.OracleDriver
            jdbc-url: jdbc:oracle:thin:@192.168.6.66:1521:orcl
            password: user_cert
            username: user_cert
